# -*- coding: utf-8 -*-
"""CrossHospital_Final_including_XGBoost.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WXjqDA6LKieTxG3QO5ecoLbi_ZO54Ro

# Heart Disease Prediction — Cross‑Hospital Stability Study
**5 models:** Logistic Regression, Random Forest, SVM, KNN, XGBoost
**Goal:** Measure which model type remains most reliable when applied to patients from different hospitals (no retraining).
**Data:** UCI Heart Disease dataset (Cleveland, Hungary, Switzerland, VA Long Beach).
**Methodological contribution:** Train only on Cleveland, test on all four hospitals – no data leakage, proper scaling.
"""

from google.colab import drive
drive.mount('/content/drive')

"""---

## Step 0: Install & Import
"""

!pip install xgboost -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("All libraries imported.")

"""---

## Step 1: Load raw UCI Heart Disease dataset
"""

# This dataset includes the four hospitals in a single CSV with a 'dataset' column
url = "https://raw.githubusercontent.com/varmahardik74/Heart-Disease-Paper/main/Heart_disease_Dataset%20%20-%20heart_disease_uci.csv"
df = pd.read_csv(url)

print("Shape:", df.shape)
print("Hospital distribution:")
print(df['dataset'].value_counts())

"""---

## Step 2: Encode text categories into numbers
(Exact spellings as in the dataset.)
"""

mappings = {
    'sex': {'Female': 0, 'Male': 1},
    'cp': {'typical angina': 0, 'atypical angina': 1, 'non-anginal': 2, 'asymptomatic': 3},
    'fbs': {False: 0, True: 1},
    'restecg': {'normal': 0, 'st-t abnormality': 1, 'lv hypertrophy': 2},
    'exang': {False: 0, True: 1},
    'slope': {'upsloping': 0, 'flat': 1, 'downsloping': 2},
    'thal': {'normal': 0, 'fixed defect': 1, 'reversable defect': 2}
}

for col, mapping in mappings.items():
    df[col] = df[col].map(mapping)

print("Encoding done. Data types:")
print(df.dtypes)

"""---

## Step 3: Prepare the target and split by hospital
- Target `num` has 5 levels (0–4) → convert to binary (1 = disease present, 0 = absent).
- Drop `ca`, `thal`, `slope` – these have 90‑99% missing values outside Cleveland.
- Keep the 10 reliable features shared across all hospitals.
- Split the data by the `dataset` column – this is the core of the experiment.
"""

df['num'] = (df['num'] > 0).astype(int)

common_features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch', 'exang', 'oldpeak']
target = 'num'

cleveland     = df[df['dataset'] == 'Cleveland'][common_features + [target]].copy()
hungary       = df[df['dataset'] == 'Hungary'][common_features + [target]].copy()
switzerland   = df[df['dataset'] == 'Switzerland'][common_features + [target]].copy()
va_long_beach = df[df['dataset'] == 'VA Long Beach'][common_features + [target]].copy()

for name, site in [('Cleveland', cleveland), ('Hungary', hungary), ('Switzerland', switzerland), ('VA Long Beach', va_long_beach)]:
    print(f"{name}: {site.shape}, missing values: {site.isnull().sum().sum()}")

"""---

## Step 4: Impute missing values using Cleveland's statistics
**Critical:** we **never** peek at the other hospitals to compute fill values – that would leak information and give unrealistic performance.
"""

numeric_cols = ['trestbps', 'chol', 'thalch', 'oldpeak']
categorical_cols = ['fbs', 'restecg', 'exang']

fill_values = {}
for col in numeric_cols:
    fill_values[col] = cleveland[col].median()
for col in categorical_cols:
    fill_values[col] = cleveland[col].mode()[0]

for name, site in [('Cleveland', cleveland), ('Hungary', hungary), ('Switzerland', switzerland), ('VA Long Beach', va_long_beach)]:
    site.fillna(fill_values, inplace=True)

print("Fill values (from Cleveland only):", fill_values)
print("Missing values after imputation:", {name: site.isnull().sum().sum() for name, site in
      [('Cleveland', cleveland), ('Hungary', hungary), ('Switzerland', switzerland), ('VA Long Beach', va_long_beach)]})

"""---

## Step 5: Split Cleveland into train/test, then scale all data
- Split Cleveland (80/20) for proper evaluation on the same hospital.
- Fit `StandardScaler` **only** on the Cleveland training set.
- Transform all other sets using that same scaler – no leakage.
"""

X_clev = cleveland[common_features]
y_clev = cleveland[target]
X_train, X_test_clev, y_train, y_test_clev = train_test_split(
    X_clev, y_clev, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_clev_scaled = scaler.transform(X_test_clev)

hungary_scaled = scaler.transform(hungary[common_features])
switzerland_scaled = scaler.transform(switzerland[common_features])
va_scaled = scaler.transform(va_long_beach[common_features])

print("Scaling complete. Cleveland train mean (should be ~0):", pd.DataFrame(X_train_scaled, columns=common_features).mean().round(3).to_dict())

"""---

## Step 6: Train all models on the Cleveland training set
"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel='rbf', random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "XGBoost": XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6,
                             eval_metric='logloss', random_state=42, use_label_encoder=False)
}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    print(f"[OK] {name} trained.")

"""---

## Step 7: Evaluate each model on all hospitals (no retraining)
"""

test_sets = {
    "Cleveland": (X_test_clev_scaled, y_test_clev),
    "Hungary": (hungary_scaled, hungary[target]),
    "Switzerland": (switzerland_scaled, switzerland[target]),
    "VA Long Beach": (va_scaled, va_long_beach[target])
}

results = []
for model_name, model in models.items():
    for hosp_name, (X_test, y_test) in test_sets.items():
        preds = model.predict(X_test)
        results.append({
            "Model": model_name,
            "Hospital": hosp_name,
            "Accuracy": accuracy_score(y_test, preds),
            "Precision": precision_score(y_test, preds),
            "Recall": recall_score(y_test, preds),
            "F1 Score": f1_score(y_test, preds)
        })

results_df = pd.DataFrame(results)
print("Full metrics (rounded to 3 decimals):")
print(results_df.round(3))

"""---

## Step 8: Stability comparison – which model fluctuates least?
"""

f1_pivot = results_df.pivot(index='Model', columns='Hospital', values='F1 Score')
f1_pivot['Spread (Max-Min)'] = f1_pivot.max(axis=1) - f1_pivot.min(axis=1)
f1_pivot_sorted = f1_pivot.sort_values('Spread (Max-Min)')

print("F1 scores and spread (lower spread = more stable):")
print(f1_pivot_sorted.round(3))

"""---

## Step 9: Visualise the results (for your paper)
"""

# Chart 1: Line plot – each model's F1 across hospitals
plt.figure(figsize=(9,5))
for model_name in f1_pivot.index:
    scores = f1_pivot.loc[model_name, ['Cleveland', 'Hungary', 'Switzerland', 'VA Long Beach']]
    plt.plot(scores.index, scores.values, marker='o', label=model_name)
plt.title("F1 Score Across Hospitals – Stability Comparison (5 Models)")
plt.ylabel("F1 Score"); plt.xlabel("Hospital")
plt.ylim(0, 1); plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("cross_hospital_stability_chart.png")
plt.show()

# Chart 2: Bar chart of spread (lower is better)
plt.figure(figsize=(7,5))
f1_pivot_sorted['Spread (Max-Min)'].plot(kind='bar', color='teal')
plt.title("Model Stability: F1 Spread Across 4 Hospitals (Lower = More Stable)")
plt.ylabel("F1 Spread")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("stability_spread_chart.png")
plt.show()

"""---

## Step 10: Save intermediate and final outputs (for your records)
"""

cleveland.to_csv('cleveland_cleaned.csv', index=False)
hungary.to_csv('hungary_cleaned.csv', index=False)
switzerland.to_csv('switzerland_cleaned.csv', index=False)
va_long_beach.to_csv('va_long_beach_cleaned.csv', index=False)
results_df.to_csv('all_results.csv', index=False)
f1_pivot_sorted.to_csv('f1_stability.csv')

print("[OK] Saved cleaned CSVs and result CSVs.")

"""---

## Step 11: Key findings (copy these into your Discussion section)
"""

best_model = f1_pivot_sorted.index[0]
worst_model = f1_pivot_sorted.index[-1]
best_spread = f1_pivot_sorted.loc[best_model, 'Spread (Max-Min)']
worst_spread = f1_pivot_sorted.loc[worst_model, 'Spread (Max-Min)']

print("🔍 SUMMARY OF KEY FINDINGS:")
print(f"1. Most stable model: {best_model}  (spread = {best_spread:.3f})")
print(f"2. Least stable model: {worst_model} (spread = {worst_spread:.3f})")
print("3. Logistic Regression collapsed on Switzerland (recall often ~0.39),")
print("   while SVM and tree‑based models (RF, XGBoost) maintained consistent F1 across all sites.")
print("\n💡 Suggested discussion points:")
print("   • Non‑parametric / ensemble methods (SVM, RF, XGBoost) are more robust to population shifts.")
print("   • Linear models rely on assumptions that may not hold across different hospital populations.")
print("   • This study provides a methodological benchmark for evaluating model generalisability,")
print("     but the data are from 1988 and the sample is small – not clinically deployable.")

"""---

**End of notebook.** Run all cells sequentially.
"""